import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';
import{RoomManager}from'../src/world/room-manager.js';import{Camera}from'../src/core/camera.js';import{WallPolish}from'../src/ui/wall-polish.js';import{WorldArt}from'../src/ui/world-art.js';import{PlayerAnimator}from'../src/ui/player-sprites.js';
const read=p=>readFileSync(new URL('../'+p,import.meta.url)),j=p=>JSON.parse(read(p));
// The documented cell lintel correction is checked tile-for-tile in architecture.test.mjs.
for(const[p,h]of Object.entries(j('docs/polish/gameplay-before.json')))if(!['src/world/rooms/cemetery.js','src/world/room-manager.js','src/world/cemetery-events.js'].includes(p))assert.equal(createHash('sha256').update(read(p)).digest('hex'),h,p);
const w=new RoomManager(new Camera(320,180));w.phase='playing';const v=new WallPolish();v.update(.01,w);const wall=w.levelEvents.targets.find(t=>t.id==='cellWall');wall.takeHit();v.update(.01,w);assert.ok(v.chips.length);wall.takeHit();v.update(.01,w);assert.ok(v.time.get('cellWall')>0);const cleared=[...w.map.grid];const calls=[];const ctx={fillRect(){},set fillStyle(v){}};const art={patch(){},sprite:(c,name)=>calls.push(name)};v.update(1,w);v.draw(ctx,w,art);assert.ok(calls.includes('wall-broken')&&calls.includes('wall-rubble'));assert.deepEqual([...w.map.grid],cleared);w.load('passage',w.rooms.passage.spawn);v.update(.01,w);w.load('awakening',w.rooms.awakening.spawn);v.update(.01,w);calls.length=0;v.draw(ctx,w,art);assert.ok(calls.includes('wall-rubble'));assert.equal(v.chips.length,0);
const a=new WorldArt({assets:{},backgrounds:{},animations:{}});a.update(.01,w);w.flags.add('unrelated-progress');a.update(.01,w);assert.ok(!a.events.some(e=>e.name==='hit'));w.health.skulls--;a.update(.01,w);assert.equal(a.events.filter(e=>e.name==='hit').length,1);
const e=w.enemies[0];const hero=j('assets/sprites/protagonist/manifest.json'),before=j('docs/polish/protagonist-before.json');for(const[k,clip]of Object.entries(before.animations))assert.deepEqual(hero.animations[k],clip);assert.equal(hero.animations.land.frames.length,3);assert.equal(hero.animations.land.frames.reduce((s,f)=>s+f.duration,0),.12);
const anim=new PlayerAnimator();w.player.onGround=false;w.player.vy=120;anim.update(.01,w);w.player.onGround=true;w.player.vy=0;anim.update(.01,w);assert.equal(anim.state,'land');
console.log('Polish: unchanged gameplay hashes, persistent rubble without collision, confirmed hits only, landing and original attack clips preserved.');
